<?php

require_once dirname(__FILE__) . '/../../../core/model/DataObject.php';

/**
 * Test class for DataObject.
 * Generated by PHPUnit on 2011-05-09 at 08:50:52.
 */
class DataObjectTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DataObject
     */
    protected $user;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->user = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }
    /**
     * Implement testSetCommitTime().
     */
    public function testSetId() {
        $this->user->setId(3);
         $id=$this->user->getId();
         echo $id;
    }

    /**
     * Implement testSetCommitTime().
     */
    public function testSetCommitTime() {
        $this->user->setCommitTime(UtilDateTime::now());
    }

    /**
     * Implement testIsNeedUpdateTime().
     */
    public function testIsNeedCommitTime() {
        $this->assertEquals(null, $this->user->isNeedCommitTime());
    }

    /**
     * Implement testIsNeedUpdateTime().
     */
    public function testIsNeedUpdateTime() {
        $this->assertEquals(null, $this->user->isNeedUpdateTime());
    }

    /**
     * Implement testSetUpdateTime().
     */
    public function testSetUpdateTime() {
        $this->user->setUpdateTime(UtilDateTime::now());
    }

}

?>
