language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script: "phpunit -c tests/phpunit.xml.dist"

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

group: stable
dist: precise
os: linux
