<?php

require_once dirname(__FILE__) . '/../../../../core/util/common/UtilReflection.php';
class EnumJsFramework extends Enum{
    const JS_FW_JQUERY="jquery";
    const JS_FW_PROTOTYPE="prototype";
    const JS_FW_EXTJS="extjs";
    const JS_FW_SCRIPTACULOUS="scriptaculous";
}
/**
 * Test class for UtilReflection.
 * Generated by PHPUnit on 2011-05-05 at 05:25:24.
 */
class UtilReflectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UtilReflection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * testGetClassStaticProperties().
     */
    public function testGetClassStaticProperties() {
        $prt=UtilReflection::getClassStaticProperties("User");
        
        print_r($prt);        
        $this->assertGreaterThan(0,count($prt),  "至少有1个静态变量");
    }

    /**
     * testGetClassConsts().
     */
    public function testGetClassConsts() {
        $prt=UtilReflection::getClassConsts("EnumJsFramework");
        print_r($prt);        
        $this->assertGreaterThan(0, count($prt), "至少有1个常量");
    }

}

?>
